version: '3.8'  # Specify the version

services:
  frontend-neogym:
    build: .
    ports:
      - '80:80'  # Corrected 'port' to 'ports' and fixed the syntax
    container_name: apache2
    volumes:
      - myapp:/var/www/html/  # Corrected 'volume' to 'volumes'
    network_mode: bridge

volumes:
  myapp:  # Added the 'volumes' section to define the named volume

