apiVersion: v1
kind: pod
metadata: 
      - name: clusterip
spec:
    selector:
        app: mypod
    type: ClusterIp
    ports:
      - protocol: TCP
        port: 80
        name: nginx
