apiVersion:  v1  #acts a manuall to your system
kind: Pod
metadata:  #like a tag
        name: mypod1
spec:
 containers:
    - name: mypod-cont1
      image: nginx:latest
      resources: 
          requests:
            cpu: "50m"
            memory: "90Mi"        
      ports:  
        - name: http
          containerPort: 80
          protocol: TCP

apiVersion: v1 
kind: Service
metadata:
    name: mypod1
spec:
  selector:
     app: mypod1
  type: NodePort
  ports:
    protocol: http
    containerPort: 80
    targetPort: 80
    name: nginx 
