apiVersion: v1  # Kubernetes API version
kind: Pod
metadata:  # Metadata for the pod
  name: mypod1
spec:
  containers:
    - name: mypod-cont1
      image: nginx:latest
      resources: 
        requests:
          cpu: "50m"
          memory: "90Mi"        
      ports:  
        - name: http
          containerPort: 80
          protocol: TCP

---
apiVersion: v1 
kind: Service
metadata:
  name: mypod1
spec:
  selector:
    app: mypod1  # Selector matches the label in the Pod
  type: NodePort
  ports:
    - protocol: TCP  # Correct protocol
      port: 80  # Service port
      targetPort: 80  # Target container port
      name: nginx
