apiVersion: v1 
kind: pod
metadata: 
      name: mypod
spec:
    containers:
          - name: mypod
            image: nginx:latest
          resourses:
                requests: 
                     cpu: "50m"
                     memory: "90Mi"
          ports:
             name: http
             containersPort: 80
             protocol: TCP