apiVersion: v1
kind: Pod
metadata: 
      name: new-app
spec:
    containers: 
        - name: mynginxpod 
          image: nginx:latest
          ports: 
              - containerPort: 80
                name: http
                protocol: TCP
