apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-deployment
  labels:
    app: todo
spec:
  selector:
    matchLabels:
      app: todo
  template:
    metadata:
      labels:
        app: todo  # Label for Service selector
    spec:
      containers:
      - name: todo-container
        image: dmirge/todo:latest  # Your DockerHub image
        ports:
        - containerPort: 80  # The port your Todo app listens on inside the container
---
apiVersion: v1
kind: Service
metadata:
  name: todo-loadbalancer
spec:
  selector:
    app: todo  # Matches the label in the Deployment
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80  # External port exposed for users
      targetPort: 80  # Target port in the container (matches containerPort)
