apiVersion: apps/v1
kind: Deployment
metadata: 
  name: todo
  labels:
    app: todo
spec:
  replicas: 14
  strategy: 
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2  # Maximum number of pods that can be created over the desired replicas
      maxUnavailable: 2  # Maximum number of pods that can be unavailable during the update
  selector:
    matchLabels:
      app: todo
  template:
    metadata: 
      labels:
        app: todo
    spec:
      containers:
        - name: http
          image: dmirge/todo:v2
          ports:
            - name: http
              containerPort: 80
              protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: todo-service
spec:
  type: LoadBalancer
  selector:
    app: todo
  ports:
    - protocol: TCP
      port: 80       # The port that the service will expose
      targetPort: 80  # The port on the container that the service will forward traffic to
