apiVersion: v1
kind: Pod
metadata:
  name: my-pod
  labels:
    app: my-pod
spec:
  containers:
    - name: my-container
      image: dmirge/student.war  # DockerHub username and image name
      ports:
        - containerPort: 8080    # Ensure this matches the app's listening port
      volumeMounts:
        - mountPath: "/usr/share/nginx/html"
          name: my-storage
      readinessProbe:
        httpGet:
          path: /
          port: 8080             # Check if the app is ready by hitting this endpoint
        initialDelaySeconds: 5    # Adjust timings based on app startup time
        periodSeconds: 10
      livenessProbe:
        httpGet:
          path: /
          port: 8080
        initialDelaySeconds: 15
        periodSeconds: 20
  volumes:
    - name: my-storage
      persistentVolumeClaim:
        claimName: my-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  type: LoadBalancer
  ports:
    - port: 80                    # External port
      targetPort: 8080            # Ensure this matches the pod container port
  selector:
    app: my-pod
