apiVersion: v1
kind: Pod
metadata:
  name: my-pod
  labels:                       # Add labels to the pod
    app: my-pod
spec:
  containers:
    - name: my-container
      image: dmirge/student:latest  # DockerHub username and image name
      volumeMounts:
        - mountPath: "/usr/share/nginx/html"
          name: my-storage
  volumes:
    - name: my-storage
      persistentVolumeClaim:
        claimName: my-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  type: LoadBalancer             # This creates an external LoadBalancer
  ports:
    - port: 8080                # External port
      targetPort: 8080           # Port on the container (adjust based on your app's port)
  selector:
    app: my-pod                  # Service routes traffic to pods with this label
