apiVersion:  v1  #acts a manuall to your system
kind: Pod
metadata:  #like a tag
        name: mypod1
        namespace: ecommercesite
        labels: 
            app: newapp
spec:
 containers:
    - name: mypod-cont1
      image: nginx:latest
      resources: 
          requests:
            cpu: "50m"
            memory: "90Mi"        
      ports:  
        - name: http
          containerPort: 80
          protocol: TCP
---
apiVersion: v1
kind:  Service
metadata: 
      name: nodeport
      namespace: ecommercesite
spec:
    type: NodePort  
    selector: 
      app: newapp
    ports:
        - port: 80
          targetPort: 80
          name: nginx
          protocol: TCP