apiVersion: v1
kind: Pod
metadata:
  name: studentlb
  namespace: serverstudent
  labels:
    app: studentlb

spec:
  containers:
  - name: serverstudent
    image: dmirge/student:micro
    resources: 
        requests:
            cpu: "50m"
            memory: "90Mi" 
    ports:
      - name: http
        containerPort: 8080
        protocol: TCP

---


apiVersion: v1
kind: Service
metadata:
  name: studentlb
  namespace: serverstudent

spec:
  type: LoadBalancer
  selector:
    app: studentlb
  ports:
  - port: 8080
    targetPort: 8080
    name: studentlb
    protocol: TCP