apiVersion: v1
kind: Pod
metadata:
  name: mypod2
  labels:
    app: mypod2
spec:
  containers:
    - name: mypod-cont2
      image: dmirge/todo
      resources:
        requests:
          cpu: "50m"
          memory: "100Mi"
      ports:
        - name: http
          containerPort: 80
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: lb
spec:
  selector:
    app: mypod2
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: todo
