apiVersion: v1
kind: Pod
metadata:
  name: todo
  namespace: servertodo
  labels:
    app: todo

spec:
  containers:
  - name: todo
    image: dmirge/todoapp:latest
    resources: 
        requests:
            cpu: "50m"
            memory: "90Mi" 
    ports:
      - name: http
        containerPort: 80
        protocol: TCP

---


apiVersion: v1
kind: Service
metadata:
  name: todoip
  namespace: servertodo

spec:
  type: ClusterIP
  selector:
    app: todo
  ports:
  - port: 80
    # targetPort: 80
    name: todoip
    protocol: TCP