apiVersion: apps/v1
kind:  ReplicaSet
metadata: 
       name: matchlabelreplicas
       labels:
            app: matchlabelreplicas
spec: 
    replicas: 3  
    template:
      metadata:  
         labels: 
            app: matchlabelreplicas
      spec:
        containers:
            - name: mypod-cont1
              image: nginx:latest
              resources: 
                  requests:
                    cpu: "50m"
                    memory: "90Mi"        
              ports:  
                - name: http
                  containerPort: 80
                  protocol: TCP
    selector:
          matchLabels:
                app: matchlabelreplicas