apiVersion: apps/v1
kind:  ReplicaSet
metadata: 
       name: podreplicain
       labels:
            app: podreplicain
spec: 
    replicas: 3  
    template:
      metadata:  
         labels: 
            app: podreplicain
      spec:
        containers:
            - name: mypod-cont1
              image: nginx:latest
              resources: 
                  requests:
                    cpu: "50m"
                    memory: "90Mi"        
              ports:  
                - name: http
                  containerPort: 80
                  protocol: TCP
    selector: 
          matchExpressions: 
            - {key: app, operator: In, values: [podreplicain, mobappreplica]}
