apiVersion: apps/v1
kind: ReplicaSet
metadata: 
     name: replicapodin
     labels: 
          app: replicapodin
spec:
    replicas: 3
    template:
       metadata:
           labels:
                app: replicapodin
      spec:
          containers:
                - name: replicapodin
                  image: nginx:latest
                  resources:
                       requests:
                       cpu: "50m"
                       memory: "90Mi"
                  ports:
                     -name: http
                     containerPort: 80
                      protocol: TCP

      selector: 
          matchExpressions: 
            - {key: app, operator: In, values: [replicapodin, mobappreplica]}
